### ISSUE TITLE
Docker image could be renamed for the sake of usability

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1053]
## Description

Current Docker image for running a Witnet full node is named `witnet/witnet-rust`, in express mention that the implementation of the Witnet protocol that is being used is the one found in this repository.

However, that poses some usability friction, as I believe that there's no good reason at this point for an end user to be exposed to the triviality of the fact that the software has been created using the Rust programming language.

Morever, `witnet/witnet-rust` has some unnecessary and unwanted repetition of the `witnet` word.

We should come with a name that is more descriptive of what the image itself does.

## Proposal

I do not have a clear proposal at this point, so I am labeling this issue as `discussion`.

So far I have thought of `witnet/node` or `witnet/full-node`, but the challenge with that is again the repetition that will happen when creating a container from it:

```console
docker run witnet/full-node node server
```

@witnet/devs @witnet/brick-mortars any better suggestion?

**Comment by tmpolaczyk** [comment]
I don't see any problems with `docker run witnet/witnet-rust node server`

**Comment by aesedepece** [comment]
Thanks @tmpolaczyk for your input.

Let's leave this here for a sprint so that other @witnet/devs can state their position, and if there's no rough consensus, I'll happily close it and go have a beer.

**Comment by bertux** [comment]
> Let's leave this here for a sprint so that other @witnet/devs can state their position, and if there's no rough consensus, I'll happily close it and go have a beer.

I'm not part of any team but now that @aesedepece has granted me push privilege after accepting my first pull requests for new integrations in operating nodes I'm looking at issues with the label operations and I like this one because it describe well the lack of meaning for the node operator in the current naming of the Docker container but I understand the current meaning to use the name of the repository it is build from.
Now that there is docker-compose integration there is no possibility of repetition in the docker-compose command line which makes life easier for everybody when I will add documentation about it as I've done for the systemd integration.
So the only remaining possible repetition is having the name of the project in the name of the container and not having the name of functionnal utility of this container which in this case is to run a node. So I like the proposal of witnet/node because node matches the word used in witnet command line.
One reason to keep the name of the project in the name of the container would be to help identify it when it's just forked in another project but everybody can choose their container name when they host it so I feel it's better to follow the KISS (Keep It Short Simple) principle.
That's just my 2 cents, personnally when I will create the new Dockerfile which install the released binaries in the container at build time instead of run time I will name it bertux/node to stay coherent with the name of the witnet component installed in this container.
As far as I know the only implementation of the node for now is in rust, so it's the default and should not need to be precised for a Docker container which by concept include the language runtime needed.
For more details you can look at https://github.com/witnet/witnet-rust/issues/1151

**Comment by aesedepece** [comment]
Sounds like this got very little interest. I'm closing it.
