### ISSUE TITLE
New bucket bug

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1055]
I have checked that there are not saving new addresses in new bucket that are different from config file

**Comment by aesedepece** [comment]
Does this mean that peer addresses that do not show up originally in the configuration file are never added to peers buckets?

I had the feeling that something in this line could be happening, as some node operators have publicly stated that they were announcing their external addresses, yet I could only discover ours and Ocuil's.

**Comment by tmpolaczyk** [comment]
* The node only accepts new peers from outbound connections.
* When an inbound connects to the node, the node stores the announced address of the inbound peer. This address is obtained from the `server_addr` field from `witnet.toml`.
* Since most of the nodes just set `server_addr = "0.0.0.0:21337"`, their public IP is not broadcasted to the network.

See the [Bucketing documentation](https://github.com/witnet/research/blob/master/p2p/p2p.md). Note that it does not mention how to treat inbound connections, whether to store their announced address or not.

**Comment by aesedepece** [comment]
This will be solved by #1136
