### ISSUE TITLE
T7.3 post-mortem

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1194]
T7.3 is in a bad condition right now. We should gather data from forked nodes, investigate what happened and come with a post-mortem document that explains the takeaways and proposes actions to take to solve existing issues.

**Comment by lrubiorod** [comment]
Attending to the data obtained from the bootstrap node logs, we can check that there were moments when EpochManager is not working, it looked like frozen by some reason.

Our hypothesis is that Azure resources for the docker images were used for compiling the bridge, so bootstrap nodes were frozen during several minutes. Due to the witnet nodes use only 4 outbounds with a 70% of consensus, if there were at least 2 bootstrap nodes in your outbounds, it would produce that you discard all your outbounds and goes to WaitingConsensus state. These nodes would stop in the process of consolidation blocks until be Synced again. If the nodes couldnt get the Synced state quickly, there would be 1 block behind the witnet chain tip. So if the initial desynched nodes length is enough big it could produce a chain reaction that moves all the nodes to WaitingConsensus in different Epochs, creating a multiple fork with multiple chain tips.

Our solution: more decentralization :P. At this moment, we have enough node operators to increase the number of outbounds. With 4 outbounds and the consensus of 70%, only 2 outbounds failing will move you to WaitingConsensus. So if we have a bigger number of outbounds we reduce the risk to be affected by a few set of nodes failing at the same moment. Moreover, it have been implemented new features that increase the synchronization process for Testnet8, a more stable synchronization process will allow to recover quickly in case of temporal desynchronization.

**Comment by tmpolaczyk** [comment]
We merged the following PRs to try to decrease the likelihood of this happening again:

PR #1209 will make nodes realize if they miss an `EpochNotification`, and stop mining to prevent forks.
PR #1212 allows nodes to keep synced if one of its peers fails, as long as 70% of the peers report the same beacon.

**Comment by aesedepece** [comment]
Is it OK to close then?
