### ISSUE TITLE
Keep UTXO set in storage

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1275]

**Comment by tmpolaczyk** [comment]
As of block 766949, the UTXO set size is 3657714 entries. The minimum size of one entry assuming no padding would be 76 bytes, which in total would be around 280MB. The real size will be greater than that because it is stored in a `HashMap`, which needs to reserve extra capacity for future insertions, and also because of any possible overhead from the `HashMap` representation.

**Comment by aesedepece** [comment]
Thanks for the info @tmpolaczyk. I think we'll all agree that 280MB is far non-negligible, and that an intentional attack to artificially grow it tenfold is perfectly feasible at near-zero cost. This starts to look prioritary to me.

**Comment by tmpolaczyk** [comment]
As of block 870368, the UTXO set size is 3728202 entries. Using the same formula as the previous calculation, that would be around 283MB. Extrapolating the difference, the UTXO set seems to be growing at a rate of 0.6816 entries per block, which translates to 99KB per day, and 36MB per year.

So under the current level of usage, the UTXO set seems to grow at a manageable rate. However it is true that this is a potential attack vector, and it increases the barriers to entry.
