### ISSUE TITLE
The bridge does not get out of including state if posting DR fails

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1293]
Apparently if the bridge fails to post a DR in the WItnet network (i.e., not enough mature UTXOs) the internal state of the DR stays in "including" and does not retry at a later point in time.

**Comment by tmpolaczyk** [comment]
The bridge assumes that `sendRequest` will never fail, and the `DataRequestTransaction` will eventually be included in a witnet block. Currently the workaround is to restart the bridge node, or to run a different bridge that will claim that request and post its proof of inclusion.

There are two situations in which the bridge can get stuck in this state:

If the `sendRequest` call fails (for example when the node has not enough balance or is not synced), the data request should be retried later, as long as the data request is still claimed by this node. This can be easily detected as there is a line in the code that says "ERROR: send request".

If the `sendRequest` call succeeds but the transaction is never included in a witnet block (because of too small fees or some double spend error), the data request should also be retried later, but we need to decide a timeout. How many witnet blocks do we want to wait before sending the transaction again, potentially with a higher fee? How do we avoid creating two transactions and getting the two included into blocks, do we need to implement a `replaceByFee` method in the node?

Ideally, the bridge should not claim any data requests until the node is synchronized, and after that it should only claim data requests if it can pay for them (and if it's profitable). But that does not solve this issue, we need to add a timeout or something that will make the node send the data request transactions to witnet again.

Conclusion: unclear, let's just add a timeout

**Comment by tmpolaczyk** [comment]
This is fixed but only if `post_to_witnet_more_than_once = true`. It would be nice to detect when the `sendRequest` call fails (for example when the node has not enough balance or is not synced), or even refrain from claiming requests if the node does not have enough balance.

**Comment by Tommytrg** [comment]
This issue belongs to the old bridge implementation
