### ISSUE TITLE
StringLength operator doesn't work as expected

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#1302]
When we use `try data request` with a data request containing `StringLenght` operator we get:

```
(random_length.json): [2020-06-12T09:08:57Z ERROR witnet_wallet::actors::app::error] Internal Error: i128 is not supported
```

**Comment by girazoki** [comment]
Not only stringLength, but also floor does not work as expected. It seems as if those operators returning i128 give this error. Furthermore the same request works in the node

**Comment by Tommytrg** [comment]
Is this the same that #1146? @tmpolaczyk

**Comment by tmpolaczyk** [comment]
> Is this the same that #1146? @tmpolaczyk

No, this issue is about i128 values that are serialized as \<error\>, while issue #1146 is about JavaScript serializing both `1.0` and `1` as `1`, therefore making them indistinguishable. But both issues would be solved if we decide to serialize integers as strings, although that's not trivial to implement.
