### ISSUE TITLE
Ensure that invalid transactions are eventually cleared from memory

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1308]
Currently, transactions are only removed from the in-memory transactions pool when they are seen inside a consolidated block. This means that invalid transactions (because of a double spend for example) will never be included in a block, they will stay in the transactions pool forever (or until the node is restarted). This may explain some issues reported by node operators about memory usage increasing over time.

The simple solution is to remove invalid transactions when mining a block. This has some problems because as the network grows, each node will mine less frequently.

Another simple solution is to periodically perform "garbage collection": validate all the pending transactions and remove the invalid ones.

Decide what to do, and check if it fixes the memory usage.

**Comment by tmpolaczyk** [comment]
> Another simple solution is to periodically perform "garbage collection": validate all the pending transactions and remove the invalid ones.

This has the problem that validating all the transactions at once may be a bad idea if the transactions pool has thousands of transactions. As an alternative, we could re-validate n transactions every epoch, where n is small (2 or 10).

Another idea is to perform this periodical validation when inserting a new transaction: for each new transaction, validate 1 or 2 old transactions and remove them if they are invalid. This has the problem that when there is a peak of new transactions, validation will take 2x or 3x more time.

And I think that the "correct" way to fix this problem is to remove all the transactions that have inputs that are included in a transaction that is included in a consolidated block. In other words, if two transactions try to spend the same UTXO, including one of them in a block removes the other one from the mempool. This would require an additional index like `HashMap<utxo, Vec<tx_hash>>`, which ironically implies more memory usage.

**Comment by aesedepece** [comment]
Even if a transaction is valid with regards of its proper construction and usage of unspent inputs, we will need to make sure that transactions don't live in the mempool forever. Otherwise, it is very poor UX for people that messes miner fees, because the UTXOs they put as input would be locked forever.

In other words, there needs to be a "mempool timeout". This seems to be the dominant approach in Bitcoin. AFAIK, miners discard transactions that have been in the mempool for more than 2 weeks. 

With that in mind, I think we could keep lists of what transactions were inserted in some time window (e.g. separated by hours), so that after the timeout we can delete the entries from that list that may still remain without having to iterate over the entire pool.

Discarding transactions that were originally valid but became invalid at a later point in time because their inputs got spent is obviously a separate problem in its own.

My hunch is that we will end up annotating the UTXOs in the UTXO set with the ID of the "potentially spending" transactions that are trying to spend them and keep that info there for as long as those transactions live in the mempool. Then, as soon as we see one of the transactions included into a block, we'll pop the UTXO from the UTXO set (which we obviously do already) and perform the deletion from the mempool of any "potentially spending" listed there.

Of course I'm assuming here that we can query the mempool by transaction hash. If not possible, instead of the hash, we can use the position inside the "inserted transactions per hour" list proposed before as a mean to recover whatever we are actually using as the index of the mempool data structure.

**Comment by mariocao** [comment]
Closed by https://github.com/witnet/witnet-rust/pull/1363
