### ISSUE TITLE
Discuss about potential changes in the mining tie-breaker algorithm

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1417]
The main problem is that many nodes are proposing a huge amount of blocks and almost none of them are being selected to be consolidated.

This problem becomes even more obvious if the reputation set does not change much in time and there is a small set of reputed nodes with high reputation.

**Comment by drcpu-github** [comment]
Leaving a comment here so I definitely don't forget to follow it. :)

**Comment by drcpu-github** [comment]
My two cents on this. It seems undesirable for node operators that the probability of minting a block can be so skewed against you that you can propose multiple hundreds of blocks with zero being accepted. Below is an example of one of my four nodes (which have been running most of this testnet). 

> Block mining stats:
> - Proposed blocks: 297
> - Blocks included in the block chain: 0
> Data Request mining stats:
> - Times with eligibility to mine a data request: 2
> - Proposed commits: 0
> - Accepted commits: 0
> - Slashed commits: 0
> The node is synchronized and the current epoch is 27613

I interpret these statistics as follows. 297 times I actually was eligible to propose a block (meaning I 'beat' the network difficulty). The set network difficulty aims to have 8 block proposals every epoch. If the odds were uniformly distributed, I would have gotten ~37 blocks accepted (I am not advocating for this to be the case, it is just an example). Given that none of the blocks were accepted, I believe this means that in all 297 cases, I was competing with at least one other node with a non-zero reputation (and thus I lost every time). I think it makes sense to give 'active' nodes an advantage, but an absolute advantage where the node with the highest reputation wins the block proposal round, seems a bit 'unfair'.

I think there are two possible issues at play here:
1) The network difficulty is not adjusted properly because the ARS size does not give a good global view on the network size (I have seen the size fluctuate between ~200 and ~500 nodes, while the total network size only grew?). This could lead to many more valid block proposals each epoch, which would in turn significantly lower the odds I get a block accepted (and would render above analysis less accurate). 
2) Because I never get a block accepted, I also never can participate in a data request, therefore I will always lose any block proposal round where an ARS node also proposes a block, which is basically a vicious circle. I heard Adan say that the aim for the ARS size is around 10% of the total nodes, which makes it very likely at least one of the 8 or more block proposing nodes is an ARS member (how is the tie broken if none of the proposing nodes are ARS members?).

I tried to game non being an ARS member by transfering some WIT from another node to an inactive one, which would make it possible for the inactive node to also solve data requests, but that did not really seem to work. That would also never work if in the end it is decided that transfered WIT is not collaterizable anymore (unless you mint a block or something along these lines).

I have two suggestions, which you are free to break down if they don't make sense or if I am missing something:
1) The easiest way to eliminate the ARS tie breaker is to just let the node with the highest proposed block hash take home the prize. I am wondering though if it is possible to game this by observing proposed blocks and just propose a new one within the window where you have to propose a block? I think this would lead to a pretty uniform distribution of proposed vs accepted blocks (which may be equally undesirable).
2) Rather than just let the highest-reputation node win, would it be possible to assign probabilites to each node winning the block proposal round based on its reputation? Say you have 8 block proposing nodes in an epoch:
    - Give each node a base chance of 5% to win the round
    - Divide the other 60% based on reputation
        - Node A has 10 reputation, node B and C have 8 and nodes D has 4, while nodes E to H have 0 reputation
        - Node A gets an extra 20% chance of winning the proposal round (total of 25% chance)
        - Nodes B and C receive 16% extra chance (total of 21% chance)
        - Node D gets 8% extra (total of 13% chance)
        - Nodes E to H stay at the 5% base chance
Would it make sense to implement something like this (and possible, e.g., through VRF's)? Obviously, percentages here are examples and can be adjusted as needed.

**Comment by aesedepece** [comment]
Hey @drcpu-github thanks for chiming in and for your detailed response.

Regarding suggestion 1, let me point out that it is not sybil-resistant. All I need to maximize my odds (and potentially take almost every block) is to operate a large number of identities such that the VRF output for at least 1 of them is high enough. 

As per suggestion 2, that's interesting indeed. Will need to further think about it.

In a more general comment, let me stress out one detail that you very correctly pointed out as issue number 2 in your analysis. In the case of nodes not in the ARS, the likelihood for a block proposal to be consolidated by a majority of the network does not only depend on the combined probability that (1) you are eligible, and (2) nobody in the ARS is eligible. There's a third combined probability that is most probably the one skewing the odds the most: the probability that nobody else out of the ARS comes up with a better VRF output.

How come? Well, the algorithm was designed like this because given the infeasibility of knowing the number of identities that are secretly computing VRFs, we basically treat all identities outside of the ARS as an abstract single identity that has a fixed base chance of proposing a block. If they are a hundred not-in-ARS identities, they all get 1% chance multiplied by the base not-in-ARS probability.

**Comment by aesedepece** [comment]
Let me sum up some stuff that was briefly mentioned when creating this issue:

- we can assume that the ARS will never represent the entirety of the network, because the ARS size is limited by block size and block period.
- thus we know that we'll always get more block candidates than targeted, so there's no need to target 8, we can simply target 1 and let _the sacred geometry of chance_ do its magic.
- favoring identities in the ARS and lumping all other identities together is still a requirement for sybil resistance.
- however, we can adjust the mechanism for breaking ties when we have multiple block candidates coming from ARS members in such a way that they all get same odds, instead of making it linear to their position in the reputation ranking.

Note that the scope of this particular issue is seeking that mining rewards are distributed more evenly. Removing the 8 candidates target surely makes it easier for not-in-ARS identities, I believe, but I don't think it will be much of a difference anyway. If we want to act on that, I think that the "mining slots" is the place to look at.

@lrubiorod and @girazoki know much more than me about the "mining slots" thingy. They can probably point to some text explaining the mechanism in detail.

**Comment by drcpu-github** [comment]
@aesedepece Thanks for the detailed response in turn. 👍 

Yes, I knew that there would be a problem with 1, it sounded way too easy to be good, but including it teached me something.

As for the mining slots, I remember exchanging a Discord message about those with @lrubiorod, and think it was modified in one of the subsequent testnets, but it appears without the desired effect (or too little of it)? Would love to read up on the mechanism in more detail though.

**Comment by mariocao** [comment]
> * however, we can adjust the mechanism for breaking ties when we have multiple block candidates coming from ARS members in such a way that they all get same odds, instead of making it linear to their position in the reputation ranking.

I personally like this idea for its simplicity! ;-)

Because it seems that the ARS is under-representing the network, most probably there much more than 4 candidate blocks per epoch. Therefore, we should first fine-tune the ARS problem and then come back to this one.

**Comment by mariocao** [comment]
Following the previous thoughts, we could consider 3 different options for the tie-breaking algorithm:

- `active` nodes
- Nodes with `reputation`
- `active` nodes with `reputation`

**Comment by mariocao** [comment]
After several discussions with @clbartoli @lrubiorod @girazoki @aesedepece and I, we are inclined to use second option of **nodes with reputation** no matter if they are active or not. It should not be too different to the third option as reputation expires with time.

**Comment by drcpu-github** [comment]
What's the reasoning behind requiring the node to have reputation (besides being active) if you'll select it at random anyway?

**Comment by mariocao** [comment]
This requirement applies only if there is a tie-break. The algorithm stays almost as it is now, but resolving the tie break between reputed nodes randomly.

Some examples to clarify it better:

- only 1 node proposes a block -> it does not matter if it has reputation or not.
- 1 proposed block from non-reputed node and 1 from node with reputation -> block of the node with reputation wins
- several blocks from nodes with reputation -> block is selected randomly from the reputed nodes (e.g. the lowest VRF from Proof of Eligibility)

This change aims to redistribute "better" the block mining rewards among those nodes that participated recently in data requests.

**Comment by mariocao** [comment]
This proposal has been merged in https://github.com/witnet/witnet-rust/pull/1442
