### ISSUE TITLE
Bug to restore peers from storage

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1422]
When you restart the node we obtain an error in peers loading from storage:

ERROR witnet_node::actors::peers_manager::actor] Couldn't get peers from storage: invalid value: integer `24350`, expected `V4` or `V6`

**Comment by aesedepece** [comment]
This is interesting, because we used to think this was a decoding error from `bincode` derived from trying to load a storage that was initialized by an older version of the node that used slightly different data structures.

However, it has been observed that this also happens after restarting nodes that use a completely fresh storage.

Therefore, this issue needs to be related to the bincode serialization of the `Peers` data structure not being perfectly symmetrical. That is, we are writing bytes into the storage that we can't decode later.

This is sort of dangerous because it could be potentially causing all buckets to go into an empty state every time we restart the node, thus rendering the peer addresses curation performed by the feeler and the icing mechanism mostly useless upon restarting.

**Comment by aesedepece** [comment]
Going to give a look at this.

**Comment by aesedepece** [comment]
> However, it has been observed that this also happens after restarting nodes that use a completely fresh storage.

I tried to reproduce this but I was not able to. No errors shown when using a fresh storage.

**Comment by aesedepece** [comment]
On an existing storage that was created with an old version, just as expected, it fails for a first time, but as soon as it overwrites the `Peers` data structure into the storage, it will no longer fail.
