### ISSUE TITLE
Superblock Sync: discard persisted and non-consolidated blocks

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1437]
Currently when the chain reorganizes we do not discard the non-consolidated blocks, leading to a client ( and the wallet) being able to still query them

**Comment by tmpolaczyk** [comment]
We can initially mark all the blocks as "non-consolidated", and then when consolidating a new superblock mark all the non-consolidated blocks that belong to the superblock as "consolidated". This way blocks from forked chains will still be available in the JSON-RPC interface, and clients can add a warning when querying non-consolidated blocks, and a bigger warning when querying non-consolidated blocks that are older than the last consolidated block, and therefore will be never consolidated.

**Comment by mariocao** [comment]
This would be really required for the wallet synchronization.
Right now under the assumption that there could be many empty blocks and empty super epochs, the wallet cannot identify which blocks can be considered consolidated or not.

**Comment by mariocao** [comment]
This issue is still as the wallet while synchronizing makes an educated guess that a block was confirmed or not by calculating the current epoch.

However, most probably this is leading to some problems if during the synchronization some of the blocks being synced are confirmed by a superblock. In that moment, the superblock notification to the wallet might be ignored (it is still syncing).

A possible solution would be to signal from the node side, which blocks are confirmed and which not (e.g. adding a flag).
From the wallet side, this information should be used inside the `sync` function (lines 660-663):

```rust
                // Compute if block should be considered confirmed
                // Note: blocks confirmed in past superblocks are considered confirmed
                // FIXME(#1437): best approach would be the node signaling if blocks are confirmed
                let node_tip_superblock_index = self.current_epoch()? / superblock_period;
                let local_tip_superblock_index = epoch / superblock_period;
                let confirmed = node_tip_superblock_index - local_tip_superblock_index > 1;
```

The confirmed `bool` should be the one passed by the node. :smile:
