### ISSUE TITLE
Discuss new reputation algorithm (trapezoid) parameters

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1496]
Discuss the parameters of the new reputation algorithm that directly affects the eligibility of identities.

**Comment by drcpu-github** [comment]
Anyone have a paper or something on which this algorithm is based? I assume [1] explains the origin? Or is this source code only?

[1] https://en.wikipedia.org/wiki/Trapezoidal_distribution

**Comment by mariocao** [comment]
In reality it is ranking-based distribution that follows a line with negative slope (looks like a triangle) and with an offset for those identities with a non-neutral reputation. However, @lrubiorod is preparing a more detailed description of the algorithm.

**Comment by lrubiorod** [comment]
The second option :P. It was an idea that we have to avoid oligarchies that we want to try in the testnet. 

That distribution correspond to a "right trapezoid" where we have as a triangle in the upper part and a rectangle in the lower [1]. The idea is to control the eligibility distribution of the reputed nodes using the triangle slope. And to keep the same difficulty for newcomers or sybils, we will add a rectangle in the lower part until complete the total area of the reputation. On this way, a newcomer has the same difficulty than before to get into, but after that, it has much more chances to solve requests and keep into the ARS, due to the differences between it and the most reputed are controlled by the slope that we choose.

Currently the we use the average (total rep/ ids with rep) as a maximum value of the triangle. With this factor the area of the triangle is (b*h/2) -> (ids * TotalRep/ids) / 2 -> TotalRep/2. If we distribute the rest of the reputation as an offset (lower rectangle), it will be (TotalRep/2)/ids -> TotalRep/(2ids). The node with less reputation will have the offset value as eligibility and the higher reputed node will have the average + offset -> TotalRep/ids + TotalRep/(2ids) -> (3TotalRep)/(2ids). It means, the most reputed node will have 3 times more eligibility than the less reputed.

Some conclusions in the discussion is to increase that factor, instead of average use 1'5*average, to modify the slope and the most reputed node would have 7 times more eligibility than the less.

[1]. 
![image](https://user-images.githubusercontent.com/44392885/91721724-7f827080-eb99-11ea-9169-54e9f515770a.png)

**Comment by drcpu-github** [comment]
Thanks for the explanation @lrubiorod.

I took a look at the original commit to figure out the final function reputation redistribution function (come on GitHub, formula markdown would be appreciated): 
```
(ID . MR - TR) / (ID . (ID - 1)) . x + (3 . TR) / (2 . ID)
MR = Minimum reputation
TR = Total reputation
ID = Total non-zero reputation identities
```

Note that whether I use round or floor, the eligibility distribution is slightly different from the example in #1460, so I imagine I am still missing a factor somewhere?
```
Example: [79, 9, 1, 1, 1, 1] -> [23, 19, 17, 14, 11, 8]
Round:   [79, 9, 1, 1, 1, 1] -> [23, 20, 17, 14, 12, 9]
Floor:   [79, 9, 1, 1, 1, 1] -> [23, 20, 17, 14, 11, 8]
```

**Comment by lrubiorod** [comment]
We are using round, but we have to take into account that we can not modify the total rep, to keep the same difficulty. So in your 2 examples of round and floor, you have more total reputation.

Currently in the code we calculate the triangle and later apply round. After that, we calculate the remaining reputation and we apply an integer division between all reputed nodes to apply the offset. Finally we apply the last reputation points one by one starting from the most reputed until the total reputation is over.

![image](https://user-images.githubusercontent.com/44392885/91845097-e155df80-ec58-11ea-8333-9d7fa523668f.png)

**Comment by drcpu-github** [comment]
Thanks, that clears up my misunderstanding. Unfortunately it does make ut close to impossible to create an clear equation for the final result.
