### ISSUE TITLE
Discuss minted collateral (rel #1295)

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1500]
Discuss about the proposal of @lrubiorod (in the PR #1295) about minted collateral.

**Comment by drcpu-github** [comment]
I liked @lrubiorod's last suggestion on this topic of allowing a fixed amount of WIT's becoming collaterizable again because of minting a block, even if they were value transferred. It closes the backdoor used by some node owners of distributing the rewards of the first (couple) of block(s) that were minted over their nodes in the hopes of increasing their data request solving chances (guilty), but that's the point of course.

I guess I may not be really up-to-date with the internal discussions related to this.

**Comment by lrubiorod** [comment]
Currently the idea of minted collateral was stopped due to other issues. Now, we are preparing the "last" testnet ( if everything is going well). So this issue is to check the pros and contras of this solution to include or not in the code

**Comment by lrubiorod** [comment]
**Conclusions**: 
- According to the behavior seen in the testnets, it looks like a really difficult task to mine a block without reputation, and this kind of solution will give a really big advantage to early adopters, making really difficult to newcomers to get into the system.
- About the dust produced by the node creating mini utxos for collaterals, the planned solution is handle UtxoSet from storage instead of RAM. And this solutions could be done after mainnet.
- By the moment, this solution is stopped until would be required
