### ISSUE TITLE
Persist the mempool to avoid invalid transactions from staying there after reorganizations

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1513]

**Comment by tmpolaczyk** [comment]
The issue is that after reorganizations, some transactions that used to be valid are now invalid because the inputs they try to spend do not exist.

Currently we have a workaround to this issue: clear the `TransactionsPool` when there is a reorganization.

The solution could be to store a snapshot of the `TransactionsPool`, similar to how the `UnspentOutputsPool` is stored. An alternative could be to remove all the transactions and validate them again, but this may be bad for performance.

**Comment by lrubiorod** [comment]
Solved in  #1756

**Comment by tmpolaczyk** [comment]
Renamed this issue to make it clear that we currently do not persist the mempool. Restarting the node clears the mempool.
