### ISSUE TITLE
Assess actor testing and present PoC

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#156]
## Context
We need some way to test Actix actors without having to start the entire node.

## Actionables
- [ ] Assess testing of Actix actors (timeboxed to 1 day)
- [ ] Add findings (if any) to documentation
- [ ] Present findings to the rest of the team

**Comment by anler** [comment]
I'll separate my findings in:

1. Terminology
2. Testing patterns
3. Tools provided by Rust
4. Actor testing

## 1. Terminology

Let's start with some terminology so we are all in the same page. When it comes to test our code, we usually end needing one of these:

- Test Double
- Monkey Patch

### Test Double

_source: https://martinfowler.com/bliki/TestDouble.html_

A Test Double describes any object you use for testing purposes that replaces a real one. They come in several flavors:

- **Dummy** objects that aren't used. Used to fill parameter lists.
- **Fake** objects that have working implementations, but that implementation takes shorctus which makes them not suitable for production (in-memory storage, no thread-safe object, etc)
- **Stub** provide canned answers to calls made during the test
- **Spy** is a Stub that also records some information based on how it was used. Used to assert how many times a method was called, with what params, etc
- **Mock** is pre-programmed with expectations which form a specification of the calls they are expected to receive

In [crates.io](https://crates.io) there are a lot of mocking libraries, but all they do is in some way automatize the creation of mocks implementing a certain trait. We could benefit from one of those but they are not a requirement for us in order to be able to test. Take for example the [mock created](https://github.com/witnet/witnet-rust/blob/722f3735797452b1041f580d60c9f16049fdc287/core/src/actors/json_rpc/json_rpc_methods.rs#L67) by tmpolaczyk

Example:

```rust
#[cfg(test)]
mod mock_actix {
    pub struct System;
    pub struct SystemRegistry;
    pub struct Addr;

    impl System {
        pub fn current() -> Self { System }
        pub fn registry(&self) -> &SystemRegistry { &SystemRegistry }
    }

    impl SystemRegistry {
        pub fn get<T>(&self) -> Addr { Addr }
    }

    impl Addr {
        pub fn do_send<T>(&self, _msg: T) {}
    }
}
```

### Monkey Patch

Is a way of extending or modifying parts of a program in ways not foreseen by the its creator. Usually if the code was written in a way that prevents or makes it very difficult to be tested, monkey patching is the way to go. Monkey patching comes with its own pitfalls and usually prevents running the tests in parallel since the _patching_ is not thread-local (this will depend on how cargo parallelizes tests and how we monkey patch).

In Rust I have found the [guerrilla](https://github.com/mehcode/guerrilla) library.

Example:

```rust
fn a() -> &'static str {
    b()
}

fn b() -> &'static str {
    "I'm b"
}

#[cfg(test)]
mod tests {
    extern crate guerrilla;
    use super::*;

    #[test]
    fn test_b() {
        assert_eq!("I'm b", b());
    }

    #[test]
    fn test_a() {
        let guard = guerrilla::patch0(b, || "I'm monkey-patched b");
        assert_eq!("I'm monkey-patched b", a());
        drop(guard);
    }
}
```

## 2. Testing patterns

In order to keep a good testing culture, we should first familiarize with the test pyramid:

![image](https://user-images.githubusercontent.com/83847/48903102-e3232a00-ee5a-11e8-8ff6-ae6f810f68f4.png)

- Ideally the more unit tests, the better, they are cheap and fast, but in order to be able to unit test without _monkey patching_, we need to use [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection) whenever possible to _decouple_ objects/functions.

Instead of having:

```rust
fn a() -> &'static str {
    b()
}

fn b() -> &'static str {
    "I'm b"
}
```

which requires monkey-patching `b` in order to unit test `a`, we could rewrite it as:

```rust
fn a_default() -> &'static str {
    a(b)
}

fn a<S>(strategy: S) -> &'static str
where
    S: Fn() -> &'static str,
{
    strategy()
}

fn b() -> &'static str {
    "I'm b"
}
```

which allows to test `a` without monkey-patching `b`, and for convenience provide an `a_default` function that is just a thin wrapper around `a` with the default dependencies.

- For functions requiring complex objects, we either could create a complete mock as tmpolaczyk did, or we can just decouple the function from the complex object by putting a trait in the middle.

This means that if we have a function like this:

```rust
fn uses_complex(a: Complex) -> bool {
    a.do_something()
}
```

we could mock `Complex`:

```rust
fn uses_complex(a: Complex) -> bool {
    a.do_something()
}

#[cfg(test)]
struct Complex;

#[cfg(test)]
impl Complex {
    fn do_something(&self) -> bool {
        true
    }
}
```

or better yet we could put an interface between:

(This example uses generic functions to benefit from static dispatch)
```rust
trait DoesSomething {
    fn do_something(&self) -> bool;
}

impl DoesSomething for Complex {
    fn do_something(&self) -> bool {
        Complex::do_something(self)
    }
}

fn uses_complex<T: DoesSomething>(a: T) -> bool {
    a.do_something()
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Simple;

    impl DoesSomething for Simple {
        fn do_something(&self) -> bool {
            true
        }
    }

    #[test]
    fn test_do_something() {
        assert!(uses_complex(Simple));
    }
}
```

or (This example uses trait objects to simplify the function signature at the cost of dynamic dispatch)

```rust
trait DoesSomething {
    fn do_something(&self) -> bool;
}

impl DoesSomething for Complex {
    fn do_something(&self) -> bool {
        Complex::do_something(self)
    }
}

fn uses_complex(a: &dyn DoesSomething) -> bool {
    a.do_something()
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Simple;

    impl DoesSomething for Simple {
        fn do_something(&self) -> bool {
            true
        }
    }

    #[test]
    fn test_do_something() {
        assert!(uses_complex(&Simple));
    }
}
```

## 3. Tools provided by Rust

As we've seen, Rust provides some tools to aid testing, but we need to change the way we structure our code in order to make it more testable.

- Generic functions to decouple concrete implementations without paying the cost of dynamic dispatch
- Trait objects to decouple concrete implementations but with the cost of dynamic dispatch
- `cfg(test)` and `cfg(notest)` for creating mocks
- The `guerrilla` library for monkey-patching (or any other we could find)

## 4. Actor testing

Now, knowing all of the above, my recommendation is that we:

- **unit test** as much library code as possible, if using dependency-injection and not monkey-patching the better
- **unit test** the actors whenever possible using the [actix mock](https://github.com/witnet/witnet-rust/blob/722f3735797452b1041f580d60c9f16049fdc287/core/src/actors/json_rpc/json_rpc_methods.rs#L67) tmpolaczyk did
- write some **integration tests** for the actors whenever needed by using a real system like I did for the [config manager](https://github.com/witnet/witnet-rust/blob/master/core/tests/config_manager_test.rs)

**Comment by aesedepece** [comment]
Done. Good job. Let's take this into account from now on!
