### ISSUE TITLE
Incorrect payment counter for address

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1815]
@drcpu-github commented on [Fri Dec 25 2020](https://github.com/witnet/sheikah/issues/1587)

**Describe the bug**
When sending multiple VTT's to one address in the Sheikah wallet (you can put me on Santa's naughty list for doing that), the payments counter is incorrect. I sent 10 VTT's to an address, but the counter only shows that address received 8 payments. I can see all transactions in the transaction view, so they are correctly indexed / discovered, but not counted in the address pane's payment counter. I think this happens when more than one VTT is included in the same block. In my example the VTT's were spread over 8 different blocks and 2 blocks each contained 2 VTT's. 

**To Reproduce**
Send multiple VTT's to one address. They should be included in the same block. The payment counter in the address pane of the Sheikah wallet only counts one per block.

**Expected behavior**
Preferably the correct amount of payments should be shown. 😄 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Sheikah v1.7.2

**Comment by tmpolaczyk** [comment]
The issue is probably in this loop:

https://github.com/witnet/witnet-rust/blob/fd5ef15fc9027361425c13edba86ce4cdd5d2f43/wallet/src/repository/wallet/mod.rs#L1263

The updated address info is created by reading the old address using `self._get_address` and adding some fields, but the updated address is not stored anywhere yet, all the updates are stored at once later on. So the solution is to check if an updated address already exists before the call to `self._get_address`, so that the updated address includes both updates.

This will fix one transaction with many outputs to the same address, but it will not fix multiple transactions in the same block, so we should search for a similar loop somewhere else.
