### ISSUE TITLE
Rescue committee creation

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1879]
According to https://github.com/witnet/WIPs/blob/master/wip-0010.md, we discuss that a Rescue Committee could help supporting the network during long rollbacks.

The Rescue Committe would always send their Superblock votes, that they would be valid for the network, but they would only be taken into account in specific moments. The Normal Committee and the Rescue Committee would be handle separately and the decision to consolidate or not a Superblock would depend of the result of both of them.

We could describe as:
 - **n1**: Normal Committee has a **consensus > 2/3**
 - **n2**: Normal Committee has a **consensus > 1/3, but < 2/3**
 - **n3**: Normal Committee has a **consensus < 1/3**
 - **r1**: Rescue Committee has a **consensus > 2/3**
 - **r2**: Rescue Committee has a **consensus < 2/3**
 

With those possibilities we could describe different situations and how should work:
- **n1 & (r1 | r2)  -> n1** (If Normal Committee has a consensus > 2/3, Rescue Committee is not needed and it will be ignored)
- **(n2 | n3) & r2 -> Rollback** (If Normal Committee and Rescue Committee have not a consensus > 2/3, it will be a Rollback equals than current flow)
- **n3 & r1 -> r1** (If Normal Committee has a consensus < 1/3, we will use the consensus achieved by the Rescue Committee)
- **n2 & r1 if n2=r1 -> n2 | r1** (If Normal Committee has a consensus < 2/3 but it is the same than the Rescue Committee consensus, that consensus will be applied)
- **n2 & r1 if n2!=r1 -> Rollback** (If Normal Committee has a consensus < 2/3 and it is different than the Rescue Committee consensus, it will be a Rollback)

With this logic, the Rescue Committee only be taken into account when the Normal Committee has not a proper consensus (n2) offering support to take a decision or using their own consensus in case of Normal Committee is in a bad state (n3), until it would be recovered to a healthy state (n1)

Moreover, the logic of reducing the committee size is not longer require, so it would reduce the possibilities that several forks could be produced when it achieved the size of 1.

**Comment by tmpolaczyk** [comment]
I tried to put the logic into a table to make it easier to understand. Is it correct?

| Normal | Rescue | Consensus                      |
|--------|--------|--------------------------------|
| N1     | R1     | N                              |
| N1     | R2     | N                              |
| N2     | R1     | if N == R then N else rollback |
| N2     | R2     | rollback                       |
| N3     | R1     | R                              |
| N3     | R2     | rollback                       |

**Comment by drcpu-github** [comment]
I have two questions:
1) How is the rescue committee built?
2) Why is a reduction in committee sizes not needed anymore? The point of reducing the size was to still try and arrive at a consensus (faster?) in the presence of voting issues (because for example miners dropped or there was a fork). With this suggestion, rollbacks can still happen, and, furthermore, I don't fully see how the issues that led to past period of weak consensus are actually solved by using a double committee?

**Comment by lrubiorod** [comment]
1. This committee is similar to the bootstrap committee and the rescue committee created during the first "BlackSunday". They were committees that support the network until it was in a proper stage, so the idea is automatize the process. Those identities could changed in the future through WIPs. Anyway, most of the time, when the network is properly working, the Rescue Committee would be ignored, it would be only useful in the bad moments
2. The reduction of the committee tried to help to arrive at a consensus, but if the network is in a very bad situation, as we see the last days, the committee decreased until arrive 1, and in that size, multiple forks are possible, and we achieve that we saw. The idea of not decrease the committee is reduce the possibilities of forks, and to achieve the consensus, we would use the support of the Rescue Committee.

In the last period of consensus, when the presence of votes decrease suddenly, the Normal Committee didn't achieve 2/3, but I suppose that it would achieve a consensus > 1/3, in that case, if the Rescue Committee would have the same superblock consensus, that superblock would be consolidated. That process would be repeated until the identities that stop signing would be removed from the ARS, and the network start to achieve a consensus > 2/3 and start to ignore the Rescue Committee again

**Comment by drcpu-github** [comment]
> 1. This committee is similar to the bootstrap committee and the rescue committee created during the first "BlackSunday". They were committees that support the network until it was in a proper stage, so the idea is automatize the process. Those identities could changed in the future through WIPs. Anyway, most of the time, when the network is properly working, the Rescue Committee would be ignored, it would be only useful in the bad moments

That is what I assumed would be proposed and I don't think this is a viable strategy for tackling the problems of "BlackSunday". Of the nodes I was watching the weekend of the breakdown (amongst others two bootstrap nodes) some of them quickly started losing consensus simply because their peers were failing (probably) and they had a hard time finding new peers. This means that even if they were part of a rescue committee and even though I had not taken them offline, they would not have been able to vote for a rescue fork. Thus, I don't really see how the introduction of this type of rescue committee will do anything simply because a part of the rescue committee might be having trouble peering, just like the larger overall network.

Ideologically speaking, it looks to me that the type of rescue committee proposed here is essentially a "centralized" version of the current superblock committee and instead of step-wise reducing the superblock committee size in the hope of achieving consensus, we just instantly jump to a small centralized vote (which may or may not work). If this is deemed necessary, why not just go for a step-wise reduction of the decentralized superblock committee first and if this does help in achieving consensus, only then go for the "centralized" vote.

Note that at the moment I don't really have a better solution. Ideally, I would like a dynamic type of (rescue) committee comprised of nodes we know were active very recently. Can we do a sort of two-tiered superblock voting where a larger committee has to first announce that they can be part of a possibly needed rescue committee?

> 2. The reduction of the committee tried to help to arrive at a consensus, but if the network is in a very bad situation, as we see the last days, the committee decreased until arrive 1, and in that size, multiple forks are possible, and we achieve that we saw. The idea of not decrease the committee is reduce the possibilities of forks, and to achieve the consensus, we would use the support of the Rescue Committee.
> 
> In the last period of consensus, when the presence of votes decrease suddenly, the Normal Committee didn't achieve 2/3, but I suppose that it would achieve a consensus > 1/3, in that case, if the Rescue Committee would have the same superblock consensus, that superblock would be consolidated. That process would be repeated until the identities that stop signing would be removed from the ARS, and the network start to achieve a consensus > 2/3 and start to ignore the Rescue Committee again

I don't think that assumption really holds? In the last fork I watched, I saw an almost clean 50/50 split of votes on different chains. I think it's fair to assume the rescue committee sees the same split. So unless the complete network immediately recovers (last time it took about 100 epochs for the split-off nodes to recover), votes will be missing because both the actual superblock committee and the rescue committee may be on different forks?

**Comment by lrubiorod** [comment]
I would like to explain some technical things first. When the node does a rollback there are 2 options:
- I have enough votes to know that there are not a consensus. In this case, rollback and move to AlmostSynced state.
- I don't have enough votes to know that there are or not a consensus (missing votes). In this case, rollback and move to WaitingConsensus state.

When you are in AlmostSynced you can consolidate blocks, send superblockvotes and you are prepared to check the beacons of your outbounds to jump to Synced state and start to mine blocks and requests. But in WaitingConsensus, you dont know if you have all the blocks of the chain or not, so you depends of your outbounds to look for the tip of the chain, in that moment, if the network is in a bad situation, the node could experiment several difficulties to find peers, and in that process could not have time to send your beacon to your peers and increase the problem. That combined with icing peers, continues rollbacks and many nodes in a same range of IPs produces a chain effect in the network.

This second behaviour I think was the problem, one or more big miner stop their nodes by any reasons, rest of the nodes don't achieve the 2/3 of the votes, because they were not sent, but they don't know if they were not sent or they only didn't receive them so, they must do a rollback and move to WaitingConsensus, where the magic happened... This is the case where a Rescue Committee could help, avoiding to move all the network to WaitingConsensus.

The first type of rollback, where there are a clean 50/50 split of votes in different chains is not a big problem, and yes, the Rescue Committe in this case, most probably has the same percentage (50/50) than the normal committee. In that case, rollback but in AlmostSynced state, where the nodes keep their peers and have information enough to continue with the chain without asking their outbounds.

Respect to the decreasing committee it was created to try to achieve a consensus faster and the network could continue, but it has some problems when something as the other days happened. Imagine we have an ARS of 10k identities, and our signing committee is 100 random identities, if 50% of that identities suddenly stop sending votes, there are so much probabilities to obtain a 50% of consensus in our signing committee, so it would produce a rollback, sometimes we would achieve luckily a 2/3 consensus, but most of the time not. If there are not new superblocks consolidated, the ARS doesn't change, and the identities that are not signing continues in it. The rollbacks continue happening, and the rest of the nodes have more difficulties to connect with other peers, and the committee starts decreasing. When the committee is lower, there are a little more probabilities to obtain 2/3 but equals to before, most of the time would 50% (of a reduced committee), so at the end we usually arrive to the big problem of a committee of only 1, where due to the connectivity problems that we were suffering during the several rollbacks, the nodes don't have a good visibility of the network and superforks (forks consolidated by a superblock) happened, and it could leave the network unrecoverable.

Our first idea was to put a floor in the decreasing committee to avoid the superforks, but after speaking about the rescue committee, we thought that it was not need it anymore, and it was more useful to have fixed size for the normal committee.

Also, I agree that the Rescue Committee is a "centralized" version of the normal committee, but most of the time, this committee would be ignored, and it also could be monitored how many superblocks are consolidated by Normal Committee, Normal Committee supported by Rescue Committee or only by Rescue Committee, to show in each moment the percentage of decentralization of the superblock consensus

**Comment by drcpu-github** [comment]
Thanks for the long explanation, even though I knew the two types of rollbacks, I was not aware of some of the more subtle differences between them.

However, I still don't see how a centralized Rescue Committee actually helps? Why do you assume that the nodes in the Rescue Committee will all be properly connected, synced and able to vote? If the rest of the network would have moved to WaitingConsensus because of missing votes due to nodes going down, I would assume the Rescue Committee will also have trouble to send it's votes around, no?

I do agree that when 50% of the ARS nodes suddenly drops, there are severe problems with the superblock committee and its reduction as was evidenced by past weak consensus episode, but that is more a problem with miner diversity at this early stage than something else and I'm not a big fan of countering that with a centralized version of the superblock committee .

**Comment by aesedepece** [comment]
I'm not assessing the background of this subject yet, because I still need to make up my mind about it. But wanted to clarify something:

> If this is deemed necessary, why not just go for a step-wise reduction of the decentralized superblock committee first and if this does help in achieving consensus, only then go for the "centralized" vote.

Step-wise reduction of the *size* of the superblock committee can help only inasmuch the lack of 2/3rd consensus is due to nodes leaving the network or being unable to get their votes out for whatever reason. But this measure is of no help when the problem is that different parts of the network are voting for different chain tips because of imperfect gossiping of block candidates—which experience tell us is the top reason for rollbacks. Under that scenario, if this measure has some effect at all, it's actually the opposite, because 2/3rds of 100 is 67% but 2/3rds of 10 is 70%.

What would actually make it easier for the network to achieve consensus in the event of severe forking rate or network segmentation would be gradually reducing the 2/3rds requirement. However, this was strongly opposed in the past because of the feeling that it traded off too much consistency and security for the sake of availability (the lower the consensus requirement, the easier you can resume the construction of the chain, but also the more likely you will end up with 2 or more valid chains).

**Comment by aesedepece** [comment]
Everyone already in this discussion has a deep knowledge of how the current superblock voting mechanism works, but I'm still reproducing a compact description of it in here, just in case anyone else ends up reading this and lacks any context on what we are talking about:

-----

A _superblock voting protocol_ exists in Withet that samples identities from the _Active Reputation Set_ (ARS), and gives those identities the right to vote on what is the current chain tip.

The messages being signed when voting are called _superblocks_, contain a cryptographic commitment to the tip of the block chain and confirm the addition of blocks to the chain just like blocks in turn do with individual transactions. 

Every 10 Witnet epochs (7.5 minutes), all nodes in the network compute whether they are eligible for voting. If they are not, they simply collect votes cast by others, and check whether their local chain tip matches the chain tip with the most votes.

In case of a match, they consolidate their chain state and consider as final every block prior to that checkpoint. Conversely, in case of a mismatch, they roll their chain state back to the one they had as of the previous consolidated superblock.

A special case exists for the situation in which no chain tip gathers a supermajority of 2/3rds of the committee, either because the number of votes that were collected is less than 2/3rds of the size of the committee, or because there exist multiple chain tips out of which none received 2/3rds or more of the votes.

In those cases, all nodes roll their chain state back to the previous consolidated superblock, and increment by 1 a _no-consensus counter_ (NCC).

When the time comes for voting the next superblock, if a chain tip gathers enough votes, everything follows normally, and the NCC is reset to 0. Otherwise, the NCC is once more increased by 1.

May the NCC hit 5, the protocol will reduce by 5 the size of the committee of identities to be sampled from the ARS. That is, if the initial committee size was 100, it will become 95.

Even if the committee size gets reduced, the same 2/3rds supermajority requirement applies. E.g. in the case of a committee of 95 identities, the amount of coincident votes needs to be equal or greater than 64; and for a committee of, say, 70 identities, 47 votes are needed.

This mechanism for adjusting the committee size works both ways: the committee size will also be increased every time that 5 superblocks are successfully consolidated without the NCC growing from 0.

As per the current protocol, the initial and maximum committee size is 100, and the minimum committee size is 1.

**Comment by aesedepece** [comment]
As a side note, I also wanted to mention something funny about this mechanism that hasn't been discussed much (probably because it's not relevant, just somehow triggering for perfectionists hahaha):

------

Incidentally, as 1 is not a multiple of 5, may the committee size ever hit the minimum and then grow back to higher sizes, the way up will follow a different progression than when descending (1, 6, 11, 16, ... vs. ..., 15, 10, 5, 1), because will only descend by 4 when going from 5 to 1, thus causing the offset. The same happens when the committee size first comes near to 100 after ever hitting 1, as the last step will be from 96 to 100.

**Comment by tmpolaczyk** [comment]
> Why do you assume that the nodes in the Rescue Committee will all be properly connected, synced and able to vote?

That's because they are assumed to be high quality nodes with active monitoring, so if something happens to one of those nodes then someone can manually restore it to a good state. Of course there are no incentives for that other than "if you don't do it the network will fork".

**Comment by drcpu-github** [comment]
> Step-wise reduction of the _size_ of the superblock committee can help only inasmuch the lack of 2/3rd consensus is due to nodes leaving the network or being unable to get their votes out for whatever reason. But this measure is of no help when the problem is that different parts of the network are voting for different chain tips because of imperfect gossiping of block candidates—which experience tell us is the top reason for rollbacks. Under that scenario, if this measure has some effect at all, it's actually the opposite, because 2/3rds of 100 is 67% but 2/3rds of 10 is 70%.

Yes, I completely agree with this observation. I just wanted to point out that if it is decided that a `Rescue Committee` like this is they way to go, I prefer an extra step of first trying `Committee Reduction`. And only after that fails a couple of times go for a centralized vote rather than immediately relying on it even if the network could have self-healed (like it has done succesfully so many times).

**Comment by drcpu-github** [comment]
> > Why do you assume that the nodes in the Rescue Committee will all be properly connected, synced and able to vote?
> 
> That's because they are assumed to be high quality nodes with active monitoring, so if something happens to one of those nodes then someone can manually restore it to a good state. Of course there are no incentives for that other than "if you don't do it the network will fork".

Yes, I realize that is the assumption, but in my experience (with my bootstrap nodes), this is not necessarily correct. I would like to think that my bootstrap nodes are pretty high-quality and they were still one of the first ones that went down (on Friday already) because they couldn't find new decent peers even with my manual intervention. The only fact they had against them is that they were running on Contabo VPS's, so the Sybil protection mechanism was stacking the cards against them.

If multiple `Rescue Nodes` in the network get dealt a bad hand of peers that went down, the `Rescue Committee` does not work. I am just advocating that I am not convinced introducing a centralized component that is essentially subject to the same rules as other network nodes is the smart move forward.

**Comment by lrubiorod** [comment]
According with some requirements for the bridge, the Rescue Committee produce some problems to implement the consolidation logic in the bridge. So that issue will be stopped by the moment
