### ISSUE TITLE
Check if `import_wallet` / `create_wallet` uses `birth_date`

### ISSUE THREAD

**Issue by gabaldon** [witnet/witnet-rust#1919]

**Comment by Tommytrg** [comment]
I've checked the `create_wallet` / `import_wallet` flows, and none of them synchronize from their creation date. So to do that, we have to make some changes both in the wallet and in Sheikah:
- [ ] Add `birth_date: CheckpointBeacon` field to `CreateWalletData` structs in order to store that field in the database.
- [ ] Add `birth_date` repository's key to store it in the database.
- [ ] `unlock_wallet` method should returns its `birth_date` so `birth_date` should be added to `WalletData` strcut.
- [ ] Modify `create_wallet` method to accept two new arguments: `birth_date` and `is_importing`
  - If `create_wallet` receives a `birth_date`, the value should be stored after validating it.
  - If `create_wallet` doesn't receive a `birth_date` but `is_importing == true` then the `birth_date` should point to the genesis.
  - If `is_importing == false` the `birth_date` is the current `CheckpointBeacon`.
- [ ] When creating a wallet, the `wallet_last_sync` should be initialized to the `birth_date`. 
- [ ] The wallet has to continue synching from the `wallet_last_sync`.
