### ISSUE TITLE
Refactor RepPoE validation tests

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1986]
In the PR #1976 there are is a lot of duplicated code in the RepPoE validation tests. The main challenge is that with each WIP, tests start to be long, repeating and difficult to maintain in case of new WIPs. The goal of this issue is to refactor those tests (and any other test that could easily be refactored in a similar manner).

**Comment by tmpolaczyk** [comment]
I did a quick survey of testing frameworks that could help with this issue but didn't find anything that would make these tests simpler.

[rstest](https://github.com/la10736/rstest) uses macros to simplify some boilerplate. I don't think that's worth it because we already use helper functions in some tests and it's not too bad.

[insta](https://github.com/mitsuhiko/insta) implements snapshot testing, which is great for the use case of "ensure that we don't accidentally break anything", but we can achieve that by simply processing all the blocks from the blockchain.

This is a great resource for testing in Rust:

https://alastairreid.github.io/rust-testability/

My main idea was to be able to run the same test under different active_wips using a helper function. The problem is that if the test fails, it is not clear why because all the logic from different protocol versions is mixed together in a single test. So I think this should only be used with one simple if condition, for example:

```rust
for_each_active_wip(
    |active_wips| {
        let res = validate_transaction(transaction, active_wips)
        // This transaction is invalid according to WIP0014
        if active_wips.wip0014() {
            assert_eq!(res, Err(TransactionError::Invalid));
        } else {
            assert_eq!(res, Ok(0));
        }
    },
)
```

The reppoe tests did not have one simple condition. Instead, after each protocol upgrade the probabilities change slightly in some cases, so I think those tests would lose quality after such a refactor. But it may be interesting to consider doing something like that in other cases.

So in PR #2000 I simply moved the tests to a `tests/` folder, and introduced the [approx](https://github.com/brendanzab/approx) crate to compare floats in tests.
