### ISSUE TITLE
Include whole transaction in send and sendRequest CLI and Wallet methods

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#2272]
Sheikah wallet can't show the transaction inputs when the user is creating a value transfer transaction because the JSONRPC methods `send` and `sendRequest` don't include the whole transaction.

Related: witnet/sheikah#1793

**Comment by aesedepece** [comment]
Blocked for now by #2261

**Comment by aesedepece** [comment]
Apparently, it was a misconception that whole transactions were not being returned back when creating VT or DR transactions in through the Wallet API. 

If we're not being able to render inputs in Sheikah it's because we are not returning a `BalanceMovement` or `WalletTransaction` along the plain transaction data (which does not contain the actual inputs but only "output pointers"). This issue is a `wontfix` but I will open a different one for assessing and implementing that other feature.
