### ISSUE TITLE
Default NTP servers tend to fail

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2303]

**Comment by tmpolaczyk** [comment]
So it turns out that the node only ever uses the first ntp server address:

https://github.com/witnet/witnet-rust/blob/2fa9a2fdae4501967d739d9884aaaef1882b02da/node/src/actors/epoch_manager/mod.rs#L147

The default config has 4 ntp servers, defined here:

https://github.com/witnet/witnet-rust/blob/2fa9a2fdae4501967d739d9884aaaef1882b02da/config/src/defaults.rs#L427-L434

But that's currently equivalent to

```rust
vec![ 
    "0.pool.ntp.org:123".to_string(), 
]
```

So we should implement some way to enable using all the ntp servers provided in the config. This way, if one of them fails, the nodes will be able to fallback to some other one. And also it is a good idea to add different sources, as to not be centralized on `ntp.org`.

Btw, I found this old issue that suggests using multiple ntp servers and taking the average (#885) so that would be another possibility.

**Comment by aesedepece** [comment]
> Btw, I found this old issue that suggests using multiple ntp servers and taking the average (#885) so that would be another possibility.

That sounds like a great option, specially if combined with adding more addresses from other providers. Because, paradoxically, decentralizing our usage of NTP can actually be a threat to consensus if more than 1/3rd of the nodes in the ARS go with a faulty, inconsistent or malevolent NTP server. That could easily bring superblock consensus down indefinitely. Moreover, the threshold could be lower than 1/3rd under the light of (a) multi-identity nodes, or (b) if it fails for a few dozen of public nodes that play a "hub" role in protocol message gossiping.

**Comment by tmpolaczyk** [comment]
Also not sure if we are implementing NTP correctly, because we only use the "receive_timestamp":

https://github.com/witnet/witnet-rust/blob/35ef5f540251a011e7deff844b043a75934805a0/util/src/timestamp.rs#L87

And we are ignoring the other fields of the NTP packet, such as the round trip delay:

```rust
pub struct Packet {
    pub leap_indicator: LeapIndicator,
    pub version: Version,
    pub mode: Mode,
    pub stratum: Stratum,
    /// 8-bit signed integer representing the maximum interval between successive messages, in log2
    /// seconds. Suggested default limits for minimum and maximum poll intervals are 6 and 10,
    /// respectively.
    pub poll: i8,
    /// 8-bit signed integer representing the precision of the system clock, in log2 seconds. For
    /// instance, a value of -18 corresponds to a precision of about one microsecond. The precision
    /// can be determined when the service first starts up as the minimum time of several
    /// iterations to read the system clock.
    pub precision: i8,
    /// Total round-trip delay to the reference clock, in NTP short format.
    pub root_delay: ShortFormat,
    /// Total dispersion to the reference clock, in NTP short format.
    pub root_dispersion: ShortFormat,
    pub reference_id: ReferenceIdentifier,
    /// Time when the system clock was last set or corrected.
    pub reference_timestamp: TimestampFormat,
    /// Time at the client when the request departed for the server.
    pub origin_timestamp: TimestampFormat,
    /// Time at the server when the request arrived from the client.
    pub receive_timestamp: TimestampFormat,
    /// Time at the server when the response left for the client.
    pub transmit_timestamp: TimestampFormat,
}
```

So most probably the clock will be off by around 50ms or whatever is the delay to the NTP server. That shouldn't be a big problem, because the witnet protocol can handle that difference, and if the delay is similar across all nodes then it is the same as having no delay, but it would be nice to fix it.

**Comment by Tommytrg** [comment]
Default NTP servers were updated and this is not a problem anymmore.
