### ISSUE TITLE
Data sources returning HTTP/300s redirects are being systematically ignored

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-rust#2305]
Instead of actually attempting a (limited) number or redirects. 

(Derived from https://github.com/witnet/witnet-price-feeds/issues/152).

**Comment by tmpolaczyk** [comment]
The HTTP client we are using, surf, allows to manually enable redirect resolving:

    let client = surf::client().with(surf::middleware::Redirect::new(5));

So we would need to decide on a maximum number of allowed redirects.

**Comment by aesedepece** [comment]
Most browsers allow 16 (Safari), 19 (Chrome and derivatives), or 20 (Firefox) redirects.

However, I believe that in practice no API would ever cause more than 1 redirect (because of URL pattern changes, rebranding of an exchange, etc), and that a limit of 3 or 4 should suffice and still avoid wasting resources.

**Comment by tmpolaczyk** [comment]
> 3 or 4 should suffice

Agree. I tried to set it to 4 on this branch (untested): https://github.com/tmpolaczyk/witnet-rust/tree/follow-http-redirects
