### ISSUE TITLE
Add support to consume the jsonrpc over HTTP, TCP and WebSockets

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#2375]

**Comment by aesedepece** [comment]
Tasklist:
- [x] Create `witty-jsonrpc`  library
- [x] Add support for TCP
- [x] Add support for WebSockets
- [x] Add support for HTTP
- [x] Actix compatibility
- [x] Publish library on Crates.io https://crates.io/crates/witty-jsonrpc
- [x] Integrate library into witnet-rust
- [ ] Fix tests (currently, they never finish because of Actix shenanigans) 
- [ ] Allow configuring JSON-RPC transports through `witnet.toml`
- [ ] Clippy, etc.
- [ ] Add documentation to library

**Comment by aesedepece** [comment]
Closed by #2377
