### ISSUE TITLE
Assess configuration parsing libraries

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#46]
We need to choose a library that is able to load configuration params from a file. The format of this config file determines the library to use.

**Comment by anler** [comment]
Since [INI](https://en.wikipedia.org/wiki/INI_file) format is a very common configuration file format for system programs, and since there seems to be a well supported library in the Rust ecosystem for parsing [TOML](https://en.wikipedia.org/wiki/TOML) named [toml](https://crates.io/crates/toml), we have decided to use that library and the TOML format (a superset of INI) to write witnet-rust's configuration file.
