### ISSUE TITLE
Transaction hash should not depend on the signatures field

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#510]
A.k.a implement segwit.

A naive solution would be to set the signatures field to an empty vector before hashing:

```rust
impl Hashable for Transaction {
    fn hash(&self) -> Hash {
        let th = Transaction { signatures: vec![], ..self.clone() };
        calculate_sha256(&th.to_pb_bytes().unwrap()).into()
    }
}
```

This is a breaking change.

**Comment by anler** [comment]
Can we think of a way that avoids cloning the entire transaction? It is a bit inefficient imho

**Comment by tmpolaczyk** [comment]
We could follow the same strategy as with blocks: move all the fields that need to be hashed to a `TransactionHeader` and hash that, but this would be a pretty big refactor.

**Comment by anler** [comment]
I guess another approach is to use [interior mutability](https://doc.rust-lang.org/reference/interior-mutability.html) so we can clear the signatures when generating the hash and restore them afterwards, for example:

![image](https://user-images.githubusercontent.com/83847/54738982-b4258680-4bb6-11e9-9ee3-1419051e7a3e.png)

This could be implemented easily but not in our case because virtually all of our abstractions in `witnet_data_structures` crate leak. Probably we should open an issue to fix this and implement [abstract data types](https://en.wikipedia.org/wiki/Abstract_data_type?oldformat=true) instead?

**Comment by tmpolaczyk** [comment]
We could also use interior mutability to cache the hash as a `cached_hash: Cell<Option<Hash>>`, because right now every call to `hash()` will have to recalculate the hash, even if the transaction has not changed. We could make all the transaction fields private and provide setters (`fn inputs_mut(&mut self) -> &mut Vec<u8>`), and set the cached hash to `None` every time a setter is called.

**Comment by aesedepece** [comment]
This may save us one copy:
```rust
impl Hashable for Transaction {
  fn hash(&self) -> u8 {
    let pb = self.to_pb();
    pb.set_signatures(vec![]);
    calculate_sha256(pb.to_bytes())
  }
}
```
However, what @tmpolaczyk suggested sounds even better to me :+1:
