### ISSUE TITLE
Assess and discuss the impact of #529 on data structures and indices

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#557]
After discussing #529, the team agreed that it proposed positive changes that may need to be implemented with relative urgency in order to reduce its side effects, which may be greater if implemented much later on.

This issue entails assessing and discussing what's the impact of #529 on the different data structures, pools and indices we have been using thus far, specially `UnspentTransactions` and `DataRequestsPool`.

**Comment by tmpolaczyk** [comment]
There are a few changes that are pretty straight-forward:

#### Eliminate input types (protocol change)
The `Input` enum should be replaced with a struct, with "input type" derived from context:
commits, reveals and tallies point to a data request, while data requests and vtts point to
value transfer outputs.

```rust
struct Input {
    output_pointer: OutputPointer,
}
```

#### Refactor the `DataRequestPool` to return Result instead of panic
This will allow to easily detect invalid blocks during validation.

#### Make reveals and tally point to the data request (now tally points to reveals, and reveals point to commits)
This way we can remove the `pointer_cache` field from the `DataRequestPool`,
greatly simplifying data request validations.

---

But the following changes require some further discussion:

#### Refactor utxo set to `HashMap<OutputPointer, ValueTransferOutput>`
Since we no longer need to store the data requests in the utxo set, it makes sense
to only store value transfer outputs, which can be created by value transfer,
data request, and tally transactions.

However, as its name suggests, the utxo set should only store keys:
`HashSet<OutputPointer>`. But if we store don't store the outputs here we must
store them in the storage, and that would require us to query the storage once
for each input we want to validate.

#### Transaction types

Currently, we have implicit transaction types:

```rust
/// Function to assign tags to transactions
pub fn transaction_tag(tx: &TransactionBody) -> TransactionType {
    match tx.outputs.last() {
        Some(Output::DataRequest(_)) => TransactionType::DataRequest,
        Some(Output::ValueTransfer(_)) => {
            if transaction_is_mint(tx) {
                TransactionType::Mint
            } else {
                TransactionType::ValueTransfer
            }
        }
        Some(Output::Commit(_)) => TransactionType::Commit,
        Some(Output::Reveal(_)) => TransactionType::Reveal,
        Some(Output::Tally(_)) => TransactionType::Tally,
        None => TransactionType::InvalidType,
    }
}
```

It would be possible to define these types in the protocol, which would make it
impossible to construct transactions with invalid type.

```rust
// Transaction types
struct CommitTransaction {
    // Inputs
    collaterals: Vec<Input>, // ValueTransferOutput
    dr_pointer: Input, // DataRequestOutput
    // Outputs
    commitment: Hash,
    pkh: PublicKeyHash, // where to receive reward
    // Proofs
    signatures: Vec<KeyedSignature>, // Proofs for collaterals (excluded from hash?)
    repoe: RePoe // Proof of elegibility for this pkh and this data request
}

struct RevealTransaction {
    // Inputs
    dr_pointer: Input,
    // Outputs
    reveal: RadonValue,
    // Proofs (must be part of the hash to avoid multiple revealers to collide)
    proof: NoncedReveal,
}

struct TallyTransaction {
    // Inputs
    dr_pointer: Input,
    // Outputs
    tally: RadonValue,
    outputs: Vec<ValueTransferOutput>, // Witness rewards
    // Proofs (none)
}

// TODO: mint transaction as a separate type?
struct MintTransaction {
    output: ValueTransferOutput,
}
```

An important question is what to do with `DataRequestTransaction`s.
Since a vtt is almost identical to a drt:

```rust
struct ValueTransferTransaction {
    inputs: Vec<Input>, // Pointer to ValueTransferOutput
    outputs: Vec<ValueTransferOutput>, // ValueTransferOutput
    signatures: Vec<KeyedSignature>, // Proofs needed to spend inputs (excluded from hash)
}

struct DataRequestTransaction {
    inputs: Vec<Input>, // ValueTransferOutput
    outputs: Vec<ValueTransferOutput>, // ValueTransferOutput
    dr: DataRequestOutput, // dr.index = outputs.len()
    signatures: Vec<KeyedSignature>, // Proofs needed to spend inputs (excluded from hash)
}
```

Using composition seems a bad idea, because the dr must change the transaction
hash, and the signatures in vtt must use that hash, otherwise anyone could modify the DataRequest!
Also, we would need to store the utxos created by this transaction in the utxo set, but
we must use the `DataRequestTransaction` hash, not the `ValueTransferTransaction` hash,
in the output pointer.

```rust
// fee = vtt.fee() - dr.total_cost()
struct DataRequestTransaction {
    vtt: ValueTransferTransaction,
    dr: DataRequestOutput,
}
```

But unifying vtts and drts may be a good idea, by adding a data_requests field to the vtt:

```rust
struct ValueTransferTransaction {
    inputs: Vec<Input>, // Pointer to ValueTransferOutput
    outputs: Vec<ValueTransferOutput>, // outputs [0, outputs.len() - 1]
    drs: Vec<DataRequestOutput>,       // outputs [outputs.len(), outputs.len() + drs.len() - 1]
    signatures: Vec<KeyedSignature>, // Proofs needed to spend inputs (excluded from hash)
}
```

Or maybe, if we remove `CommitOutput`, `RevealOutput` and `TallyOutput`:

```rust
struct Transaction {
    inputs: Vec<Input>, // Pointer to ValueTransferOutput
    outputs: Vec<Output>, // Either ValueTransferOutput or DataRequestOutput
    signatures: Vec<KeyedSignature>, // Proofs needed to spend inputs (excluded from hash)
}
```

But wait, this is identical to our current definition of `Transaction`.
So maybe we just need to remove `CommitOutput`, `RevealOutput` and `TallyOutput`
and instead use the special `CommitTransaction`, `RevealTransaction` and `TallyTransaction`.

It should be noted that `TallyTransaction`s are somewhat different from commits and reveals,
because they create outputs which need to be inserted into the utxo set.

To summarize:
- Merge `DataRequestTransaction` with `ValueTransferTransaction`? How?
- Make `MintTransaction` a separate type or a special case of `ValueTransferTransaction`?
- Remove `CommitOutput`, `RevealOutput` and `TallyOutput` by turning them into `CommitTransaction`, `RevealTransaction`, `TallyTransaction`?

#### Segregating transactions in blocks

Now, if we decide to discriminate transactions at a protocol level, we can also
segregate transactions in the block structure:

```rust
// Current
struct Block {
    pub block_header: BlockHeader,
    pub proof: LeadershipProof,
    pub txns: Vec<Transaction>,
}

// Proposed
struct Block {
    pub block_header: BlockHeader,
    pub proof: LeadershipProof,
    pub txns: TransactionList,
}

struct TransactionList {
    mint: MintTransaction,
    vtts: Vec<ValueTransferTransaction>,
    drs: Vec<DataRequestTransaction>,
    commits: Vec<CommitTransaction>,
    reveals: Vec<RevealTransaction>,
    tallys: Vec<TallyTransaction>,
}
```

This would slightly simplify validation, and we could add magic rules to
dedicate some space to commits and reveals in order to incentivize cooperation.

A slightly less radical alternative would be to require transactions to be ordered inside a `Vec<Transaction>`.
TODO: how does protocol buffers encode a vector of enums?
Do all the elements in the vector get padded to the lenght of the biggest variant? (like in Rust)

---

#### ChainState summary

```rust
// Old implementation:
pub type Blockchain = BTreeMap<Epoch, Hash>;
pub struct ChainState {
    /// Blockchain information data structure
    pub chain_info: Option<ChainInfo>,
    /// Unspent Outputs Pool
    pub unspent_outputs_pool: HashMap<OutputPointer, Output>,
    /// Collection of state structures for active data requests
    pub data_request_pool: DataRequestPool,
    /// List of consolidated blocks by epoch
    pub block_chain: Blockchain,
}

pub struct ActiveDataRequestPool {
    /// Currently active data requests for which this node has announced commitments
    /// Key: Data Request Pointer, Value: Reveal Transaction
    pub waiting_for_reveal: HashMap<OutputPointer, Transaction>,
    /// Indexes the output pointers of every active data request by epoch (only for mining purposes)
    pub data_requests_by_epoch: BTreeMap<Epoch, HashSet<OutputPointer>>,
    /// Indexes every active data request by its original output pointer
    pub data_request_pool: HashMap<OutputPointer, DataRequestState>,
    /// Lists data request reports that need to be persisted into storage
    pub to_be_stored: Vec<(OutputPointer, DataRequestReport)>,
    /// Maps `commit_pointer` and `reveal_pointer` to `data_request_pointer`
    pub dr_pointer_cache: HashMap<OutputPointer, OutputPointer>,
}

// New proposal:
pub type Blockchain = BTreeMap<Epoch, Hash>;
pub struct ChainState {
    /// Blockchain information data structure
    pub chain_info: Option<ChainInfo>,
    /// Unspent Outputs Pool
    pub unspent_outputs_pool: HashMap<OutputPointer, ValueTransferOutput>,
    /// Collection of state structures for active data requests
    pub data_request_pool: DataRequestPool,
    /// List of consolidated blocks by epoch
    pub block_chain: Blockchain,
}

pub struct ActiveDataRequestPool {
    /// Currently active data requests for which this node has announced commitments
    /// Key: Data Request Pointer, Value: Reveal Transaction
    pub waiting_for_reveal: HashMap<OutputPointer, RevealTransaction>,
    /// Indexes the output pointers of every active data request by epoch (only for mining purposes)
    pub data_requests_by_epoch: BTreeMap<Epoch, HashSet<OutputPointer>>,
    /// Indexes every active data request by its original output pointer
    pub data_request_pool: HashMap<OutputPointer, DataRequestState>,
    /// Finished data requests (stored in storage?)
    //pub data_requests_done: HashMap<OutputPointer, DataRequestReport>,
    /// Lists data request reports that need to be persisted into storage
    pub to_be_stored: Vec<(OutputPointer, DataRequestReport)>,
    /// Maps `commit_pointer` and `reveal_pointer` to `data_request_pointer`
    // Not needed because now reveal and tally point to the data request
    //pub dr_pointer_cache: HashMap<OutputPointer, OutputPointer>,
}
```

The changes in the `ChainState` structure are relatively minor.
