### ISSUE TITLE
Assess Smart Mining

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#604]

**Comment by tmpolaczyk** [comment]
Mining lacks the following validations: 

### Value Transfer Transactions
* Inputs must be in the utxo set, or in other transactions which are also added in this block. 
* If more than one transaction tries to spend the same input, pick the one with highest fee and remove the others.

Utxos that will never be spendable should be removed from the mempool.

### Data Request Transactions
* Check that this data request does not already exist in the data request pool (wouldn't be needed under the assumption of impossibility to create the same data request with the same inputs more than once, but that can be done by using the mint transaction).

### Commit Transactions
Under the registers model, most of these validations would be done implicitly by a `get_commits_for_mining()` method on an hypothetical `DataRequestTransactionsPool`.
* Check that the data request exists and is in commit stage.
* Check that the total number of commits is correct.
* Check that all the commits were done in the same epoch.

### Reveal Transactions
Under the registers model, most of these validations would be done implicitly by a `get_reveals_for_mining()` method on an hypothetical `DataRequestTransactionsPool`.
* Check that the data request exists and is in reveal stage.
* Check that the total number of reveals is correct.

### Tally Transactions
Since tally transactions are created by the miner, we can assume that they are valid.

However: currently, if any consensus script fails, mining fails, because we use `join_all` to collect all the futures and `join_all` stops on the first error.
This can be quickly fixed by mapping `Ok(T) => Ok(Some(T))` and `Err(_) => Ok(None)`, and then applying a flat_map.
But when a consensus script fails, that error should be reported as the result of the data request, so the current behavior seems incorrect.

**Comment by tmpolaczyk** [comment]
Further work will be tracked in separate issues:

#631
#632
