### ISSUE TITLE
`installation guide` link on repo leads to wrong page

### ISSUE THREAD

**Issue by jrmoreau** [witnet/witnet-rust#751]
On the main page of witnet-rust the hyperlink of `installation guide` leads to [https://docs.witnet.io/get-started/install](https://docs.witnet.io/get-started/install) which is a 404, rather than just sending user to the docs at [https://docs.witnet.io/](https://docs.witnet.io/)

**Comment by Sighery** [comment]
To add to this, in the same README, both the `contributing guide` and `Installation, compilation and development instructions` hyperlinks under the `Contributing` section lead to 404 pages.

I was considering sending a PR to fix the `installation guide` hyperlink, but not sure the current https://docs.witnet.io/ is a good replacement, since it leads you to what it seems more of an introduction page rather than an installation one. Maybe https://docs.witnet.io/try/run-a-node/ would be a better fit for that description? Not sure.

Also not sure what the other two hyperlinks should be pointing to. Perhaps https://docs.witnet.io/community/contributing/ for `contributing guide`? Unsure of which page would apply for `installation, compilation and development instructions`.

**Comment by aesedepece** [comment]
Hi Sighery,

Thanks for your comments and feedback.

We recently replaced the documentation altogether for a newer version. All
links to the documentation need to be reconsidered and updated accordingly.

We'll be fixing it in the next few days. Please beat with us!

**Comment by aesedepece** [comment]
*bear

**Comment by Sighery** [comment]
Yeah, I figured that was the case. I remember reading a different documentation some weeks/a month ago, and those links I believe worked at the time. Still, figured I'd report the other broken links so it's all documented in the same issue for easier fixing.

**Comment by wimel** [comment]
- On the doc [Runing `witnet-rust` from source code](https://github.com/witnet/witnet-rust/blob/master/docs/get-started/installation/from-source.md) the link to the [Witnet-rust CLI documentation](https://github.com/witnet/witnet-rust/blob/master/docs/get-started/installation/from-source.md#run-with-cargo) it's broken, I think the correct link should be [this](https://github.com/witnet/witnet-rust/blob/15d1c86e3c45dbb68653fd9c3b8d484b592547ae/docs/interface/cli.md).

- In [Compilation dependencies](https://github.com/witnet/witnet-rust/blob/master/docs/get-started/installation/from-source.md#compilation-dependencies)  it should be good to add the package `pkg-config` _(I have [this](https://pastebin.com/Yj60pD6z) error during install using this steps)_

**Comment by tmpolaczyk** [comment]
Fixed in #1135
