### ISSUE TITLE
[Pseudo-WIP]: Deprecation of tally scripts in favor of tally filters + reducer

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#912]
- Remove Tally script
- Tally struct with 3 fields:
   - min_consensus -> minimum value (witnesses or percentage) to consider that tally aggregation is right.
   - filter -> optional filter that punish filtered reveals
   - reducer -> reducer to obtain the final result
- Create "flatten/abort filter" which uses the min_consensus value. This function returns error in case of error results overcome non-error parameter indeed by the min_consensus value. In the other case, filter and punish error values, and later continues with the new tally script.
- New tally script doesn't come from the data requester. Instead of that, the tally miner will create a tally script with the filter and the reducer specified for the data requester. On this way, it is easier to specify which filters and reducers are valid in tally and could be validated in the DataRequest transaction. DataRequest with invalid filters or reducers could be skipped at the beginning, and they will not be included in the pools

**Comment by aesedepece** [comment]
```
Pseudo-WIP: #912
Title: Deprecation of tally scripts in favor of tally filter + reducer
Status: Draft
Type: Standards Track
```

## Abstract

This is a proposal for improvement of the way in which tally stage logic is expressed in Witnet requests. It aims to improve the security of tally logic through limiting the negligent use of dangerous RADON operators, and in general to enhance the conciseness of the protocol's data structures.

## Motivation

Witnet allows parametrization of many of the logic that witnessing nodes will execute throughout the different stages of the request life cycle.

An aggregation function is a Witnet script that defines how to reduce the result of multiple sources into a single data point. They are similar to Javascript's `.reduce()` method or the `fold` higher-order function from many programming languages.

Tally functions are really similar to aggregation functions, but instead of aggregating multiple sources, they aggregate the results reported by multiple Witnet nodes.

Even since we started implementing RADON as the scripting language for Witnet requests, we have identified many operators that could potentially introduce spurious incentives or in general harm the system when used in certain stages.

Namely, the use of sorting operations, accessors and ranges on the `Array` type during the tally stage is specially dangerous, as the output of tally scripts is used for deciding which witnessing identities get rewarded (through reputation gains plus a share of the rewards) and which get punished (exclusively through reputation loss).

All those observations lead to issues like #904 and #910, which aimed to forbid the use of specific operators in the tally stage. However, when discussing those issues, we realized that the restrictions needed for ensuring the integrity of tally go beyond forbidding specific operators.

One restriction that is currently not necessarily being honored is for the tally function to follow the following signature:

```rust
// Using Rust notation here just as a standard way to express the function's signature
fn tally_function<T>(reveals: Array<T>) -> T {}
```
Our believe is that any function satisfying this signature—which corresponds to the typical `fold` or `reduce` in many programming languages—should suffice as a tally function. If we want a request to have a different output type, there's no need to map (`fn map<T, U>(input: Array<T>) -> Array<U> {}`) at this stage: we can just do the mapping at the end of the aggregation stage.

Following this reasoning, tally logic should only contain two things:
- Zero or more pre-compiled filters
- One pre-compiled reducer

Precompiled filters and reducer are those using a filtering or reduction logic that is natively implemented in the RADON engine and therefore do not need a subscript as an argument, only the identifier of the precompiled function.

At this point, it becomes apparent that tally scripts are no longer needed, and can be replaced by two separate schema fields containing the identifiers of the precompiled filtering and reduction functions.

## Specification

This proposal entails the following changes:
- Removing the `value` field from the `DataRequestOutput` structure.
- Adding a `witness_reward` to the `DataRequestOutput` structure.
- Removing the `value / witnesses` integer division validation.
- Modifying the cost computation function so it follows the cost model below.
- Adapting all `DataRequestOutput` and `DataRequest` factories.
- Adapting all JS libraries, including [witnet-requests-js] and [Sheikah].
- Adapting all examples in the [witnet-rust] repository.

## Backwards-compatibility assessment
### Consensus
This proposal is a breaking change to consensus and thus can only be adopted either through a soft or hard fork. As long as we are in rebootable testnet stage, the latter way is suggested.

### Examples
This proposal renders all JSON examples outdated and not valid under the new cost model and validation rules.

Examples using [witnet-requests-js] and [truffle-box] are also affected, as the `Tally` class should no longer inherit from `Script` and there's no need for proxifying the class to make it operable.

### Libraries and clients
The [witnet-requests-js] library needs to adopt the specified changes and a new release needs to be published.

Namely,  the `Tally` class should no longer inherit from `Script` and there's no need for proxifying the class to make it operable. It can be modeled in the likes of:

```js
class Tally {
  constructor(reducer, filters = []) {
    this.reducer = reducer;
    this.filters = filters;
  }
}
```


[Sheikah] has no support for deploying requests yet, so it is unaffected.

### Documentation
The new specification has no impact on documentation, as it follows what it is already documented.

## Acknowledgements
This proposal emerged after a convo with @lrubiorod, who detailed the current situation and gave feedback on the specification found herein.

[examples]: https://github.com/witnet/witnet-rust/tree/master/examples
[witnet-rust]: https://github.com/witnet/witnet-requests-js
[witnet-requests-js]: https://github.com/witnet/witnet-requests-js
[truffle-box]: https://github.com/witnet/truffle-box
[Sheikah]: https://github.com/witnet/witnet-requests-js

**Comment by tmpolaczyk** [comment]
What about filters that need an argument? For example, the standard deviation filter needs an argument (number of sigmas), do we want to allow using it? Or forbid any filters that need arguments?

**Comment by aesedepece** [comment]
Oops that's right, it should be a `RadonCall`, not an `uint8`.

`RadonCall` is roughly defined as `(uint8, Vec<uint8>)`.

**Comment by lrubiorod** [comment]
> Oops that's right, it should be a `RadonCall`, not an `uint8`.
> 
> `RadonCall` is roughly defined as `(uint8, Vec<uint8>)`.

But RadonCall is `(RadonOpCodes, Option<Vec<Value>>)`
`RadonOpCodes` is a `uint8` but an `Option<Vec<Value>>` is not quite similar to `Vec<uint8>`
Maybe I could use a similar struct that could be converted to a `RadonCall` in the moment to create a script

**Comment by aesedepece** [comment]
That's why I wrote "roughly". My point was that it can be easily covered
from one format to another hehehe
