### ISSUE TITLE
Handle RadErrors in tally building

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#935]
As commented in #912, we need a "flatten" filter that decides if exist an error consensus or not. And in case of non error consensus, the nodes that reveals a RadError must to be punished, before to apply the new Tally script

**Comment by aesedepece** [comment]
Rather than a filter, that'd be a "tally precondition clause", right? If
the clause passes (majority of valid reveals), filter/reducing is applied
and punishments work as expected. If the clause fails, the entire request
is aborted, finishes with an error and there are no punishments. Am I
missing something?
