### ISSUE TITLE
Simultaneous panic on many nodes with `Transport endpoint is not connected`

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#992]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', src/libcore/result.rs:1165:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: __libc_start_main
  34: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread.
```

**Comment by aesedepece** [comment]
Just for the record, this kind of panics is most times produced by a fatal error in the storage backend, e.g. a faulty drive or a completely full file system.

**Comment by aesedepece** [comment]
This just happened to `witnettestnet7dot1_node_server_1_1` without evidence of it being a storage backend fault. Reopening.

**Comment by tmpolaczyk** [comment]
Thanks to @lrubiorod we got a backtrace :pray: 

![imagen](https://user-images.githubusercontent.com/44604217/84769446-22354500-afd6-11ea-9830-cbf8a5ffa2ed.png)

It looks like the problem is the one unwrap from here:

https://github.com/witnet/witnet-rust/blob/05f8a58cdb60212dc193f5d5932b5068352024f8/node/src/actors/sessions_manager/handlers.rs#L58

I think this happens if the session disconnects before we get a change to get the remote addr. That's a pretty strange library limitation, but ok.

The solution is to handle that unwrap, for example do not start the actor in that case. `Actor::create` does not support error handling, there is no `Actor::try_create`. But we can just inline that method and add an `if let Ok` somewhere:

```rust
        // This is Actor::create
        let mut ctx = Context::new();
        let act = f(&mut ctx);
        ctx.run(act)
```
